version: 2
jobs:        
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Validate ami
          command: 
packer build  \
    -var 'aws_access_key=AKIAQ7IKVIAKB4RAC2G6' \
    -var 'aws_secret_key=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' \
    -var 'aws_region=us-east-1'  \
    -var 'subnet_id=subnet-e754e6c6'  \
    -var 'ami_users=359410113455' \
    -var 'source_ami=ami-0817d428a6fb68645'  \
    ami.json
      - run:
          name: build ami
          command: 
packer build  \
    -var 'aws_access_key=AKIAQ7IKVIAKB4RAC2G6' \
    -var 'aws_secret_key=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' \
    -var 'aws_region=us-east-1'  \
    -var 'subnet_id=subnet-e754e6c6'  \
    -var 'ami_users=359410113455' \
    -var 'source_ami=ami-0817d428a6fb68645'  \
    ami.json

workflows:
  version: 2
  build-workflow:
    jobs:
      - build